services:
  mysql:
    image: mysql:8.0
    container_name: slack-bot-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slackbot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: ./migrations
      dockerfile: Dockerfile
    container_name: slack-bot-migrations
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      mysql:
        condition: service_healthy

  elasticmq:
    image: softwaremill/elasticmq
    container_name: slack-bot-elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9324"]
      interval: 10s
      timeout: 5s
      retries: 5

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: slack-bot-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: slack-bot-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  dynamodb-data:

networks:
  slack-bot-network:
    driver: bridge
